version: "3" #версія протоколу
services:
  php:
    container_name: php_pro #назва контейнеру
    build:
      context: ./ #точка входу (папка php-lessons-pro)
      dockerfile: "docker/configs/php/Dockerfile" #налаштування для php
    environment:
      XDEBUG_CONFIG: "remote_host={{yourIP}}"
      PHP_IDE_CONFIG: "serverName=docker"
    volumes:
      - ./:/srv/src/php_pro #(точка входу):(робоча директорія в серидині контейнера)/синхронізує папки в обидва бокивщслук
  db_mysql:
    image: mysql:latest
    container_name: php_pro_mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_CONNECTION: db_mysql
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: Bisix21
      MYSQL_DATABASE: php_pro
      MYSQL_PASSWORD: password
